eureka:
  instance:
    appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:18800/eureka/  #注册中心地址

spring:
  datasource:
    url: jdbc:mysql://192.168.0.100:3307/bc_mars?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    initialSize: 10
    minIdle: 10
    maxActive: 2000
    maxWait: 60000
  redis:
    host: 192.168.0.101
    port: 6379
    password: '000000'

mars:
  swagger:
    token: bearereyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MjQ4ODYwMjksInVzZXJfbmFtZSI6IjExMSIsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiIyNzc2MjA2NC1jY2ZlLTQ0MDYtOGU2Zi1hN2IzMTBkMDcxMjgiLCJjbGllbnRfaWQiOiJjbGllbnRfbWFycyIsInNjb3BlIjpbInNjb3BlX21hcnMiXX0.aY9ITeUUWe8bSKdlPtlsqQHEzGFFYS79joaxYibOGukml4ri4Eq8VzqpJ9LI48QwU9fcQzF45Mjehe1R7LMdCrbBLFmVMBYA21OXd6SdmOp2Hma_QCZ6DOv2S69vhwmDtFohEBhq7rSKzpLzttJ8Cv_hbGIlnXwnlKZyBJtd4OU
