server:
  port: 18890

spring:
  application:
    name: mars-task

mars:
  swagger:
    title: Mars Cloud
    desc: Task RESTful接口说明文档
    version: 1.0
  oauth2:
  	client:
  	  tokenServiceId: mars-oauth2
  	  clientId: client_service
  	  clientSecret: 1qasw2zxc
  	  scope: scope_all