eureka:
  instance:
    appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:18800/eureka/  #注册中心地址

spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    name: druid
    druid:
      min-idle: 1000
      max-active: 2000
      max-wait: 6000
      initial-size: 5
  redis:
    host: 192.168.0.101
    port: 6379
    password: '000000'

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  offsetAsPageNum: true
  rowBoundsWithCount: true

mars:
  swagger:
    token: bearereyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MjQ4ODYwMjksInVzZXJfbmFtZSI6IjExMSIsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiIyNzc2MjA2NC1jY2ZlLTQ0MDYtOGU2Zi1hN2IzMTBkMDcxMjgiLCJjbGllbnRfaWQiOiJjbGllbnRfbWFycyIsInNjb3BlIjpbInNjb3BlX21hcnMiXX0.aY9ITeUUWe8bSKdlPtlsqQHEzGFFYS79joaxYibOGukml4ri4Eq8VzqpJ9LI48QwU9fcQzF45Mjehe1R7LMdCrbBLFmVMBYA21OXd6SdmOp2Hma_QCZ6DOv2S69vhwmDtFohEBhq7rSKzpLzttJ8Cv_hbGIlnXwnlKZyBJtd4OU
  oauth2:
    client:
      accessTokenUri: http://mars-oauth2/oauth/token
      tokenServiceId: mars-oauth2
      clientId: client_service
      clientSecret: 1qasw2zxc
      scope: scope_all
