server:
  port: 18880

spring:
  application:
    name: mars-biz

mars:
  swagger:
    title: Mars Cloud
    desc: Biz RESTful接口说明文档
    version: 1.0
  oauth2:
    client:
      tokenServiceId: mars-oauth2
      clientId: client_service
      clientSecret: 1qasw2zxc
      scope: scope_all