server:
  port: 18820

spring:
  application:
    name: mars-common
    
security:
  oauth2:
    resource:
      filter-order: 3

mars:
  swagger:
    title: Mars Cloud
    desc: Common RESTful接口说明文档
    version: 1.0