server:
  port: 18820

spring:
  application:
    name: mars-oauth2
    
security:
  oauth2:
    resource:
      filter-order: 3

mars:
  swagger:
    title: Mars Cloud
    desc: Oauth2 RESTful接口说明文档
    version: 1.0
  oauth2:
    client:
      tokenServiceId: mars-oauth2
      clientId: client_service
      clientSecret: 1qasw2zxc
      scope: scope_all